[package]
name = "loadtester_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
futures = "0.3.21"
serde_yaml = "0.8.26"
tokio = { version = "1.20", features = ["full"] }
